name: CI
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 18
      - name: Install Chrome and ChromeDriver
        # - uses: actions/checkout@v2
        uses: nanasess/setup-chrome@v2
        with:
          chrome-version: stable
          chromedriver-version: 114.0.3
      - name: Install
        run: npm install
      - name: Test
        run: npm run wdio
      - uses: actions/upload-artifact@v1
        if: failure()
        with:
          name: logs
          path: logs
