name: CI
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install
        run: npm install

      - name: Test
        run: npm run wdio
      - uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: logs
          path: logs
      - name: Commit report results
        if: always()
        run: |
          git checkout report
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add testReports/allure-report -f
          git add testReports/allure-results -f
          git commit -m "[chore] autogenerate Allure report" -a
      - name: Push changes
        if: always()
        uses: ad-m/github-push-action@report
        with:
          github_token: "${{ secrets.GITHUB_TOKEN }}"
          force: true

      # - name: Commit and push changes
      #   run: |
      #     git checkout report
      #     git add allure-report allure-results
      #     git commit -m "Generating resports"  # Commit the changes

      #     git remote set-url origin "https://github.com/${{ github.repository }}"
      #     git push origin report
