name: CI
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16

      # - uses: browser-actions/setup-chrome@v1
      # - run: chrome --version

      # - name: Install Chrome and ChromeDriver
      #   uses: nanasess/setup-chromedriver@v2

      - name: Install
        run: npm install

      - name: Test
        run: npm run wdio
      - uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: logs
          path: logs
